controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - MotorJointLeft
      - MotorJointRight

forward_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - MotorJointLeft
      - MotorJointRight

forward_acceleration_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - MotorJointLeft
      - MotorJointRight
    interface_name: acceleration